# Generated by Django 2.2.14 on 2022-12-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChipWeb', '0003_auto_20221113_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Engine', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=50)),
                ('kw', models.CharField(max_length=50)),
                ('kWA', models.CharField(max_length=50)),
                ('nM', models.CharField(max_length=50)),
                ('nMA', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Fuel', models.CharField(max_length=50)),
            ],
        ),
    ]
